function [varargout] = imageinfo(varargin)
%GUI to display some information and possibility to copy it to clipboard.
%Used for image stack info, export info, etc.

%Moved from tools.m and refactored by Justine Le Douaron, Medviso, 2022

%#ok<*GVMIS>

if nargin == 0
  varargin = {'init'};
end

if (nargout)
  [varargout{1:nargout}] = feval(varargin{:}); % FEVAL switchyard
else
  feval(varargin{:}); % FEVAL switchyard
end

%-------------------------------
function init(figtitle,string)
%-------------------------------
%Init GUI
global DATA

if ~DATA.DataLoaded
  return;
end

%Get input arguments
if nargin < 2
  string = getdefaultstring;
end

if nargin < 1
  figtitle = getdefaulttitle;
end

%Create figure
DATA.GUI.ImageInfo = mygui('imageinfo.fig');

%Get global variables
gui = DATA.GUI.ImageInfo;
guih = gui.handles;
myadjust(gui.fig);

%Set figure title
set(gui.fig,'Name',figtitle);

%Set string
gui.string = string;

% Display in GUI
set(guih.infolistbox,'string',gui.string,'fontname',get(0,'fixedwidthfontname'),'Fontsize',14)

%------------------------------
function stri = fixstring(stri)
%------------------------------
% Remove null terminators in the middle of the string.
% Can appear when reading DICOM headers.

stri8 = int8(stri);
stri8(stri8 == 0) = 32; % 32 = space
stri = char(stri8);

%------------------------------
function title = getdefaulttitle
%------------------------------
%Return the default title of the GUI.
title = dprintf('Image Info');

%------------------------------
function str = getdefaultstring
%------------------------------
%Return the default string to display in the GUI.
global DATA SET NO

if isempty(SET(NO).FieldStrength)
  fieldunit = '';
else
  fieldunit = '[T]';
end
if isempty(SET(NO).EchoTime)
  SET(NO).EchoTime = 0; % this is default value when EchoTime tag does not exist, also applied in loadfieldhelper for empty EchoTime field
end

if DATA.issegment3dp
  %3DP version
  str = {
    fixstring(sprintf('OrigFileName:        %s',SET(NO).OrigFileName)),...
    fixstring(sprintf('Scanner:             %s',SET(NO).Scanner)),...
    fixstring(sprintf('Modality:            %s',SET(NO).Modality)),...
    fixstring(sprintf('AcquisitionDate:     %s',SET(NO).PatientInfo.AcquisitionDate)),...
    fixstring(sprintf(['AcquisitionTime:     ', segtime2clock, ' [hh:mm:sec]'])),...
    fixstring(sprintf('XSize:               %d',SET(NO).XSize)),...
    fixstring(sprintf('YSize:               %d',SET(NO).YSize)),...
    fixstring(sprintf('ZSize:               %d',SET(NO).ZSize)),...
    fixstring(sprintf('TSize:               %d',SET(NO).TSize)),...
    fixstring(sprintf('AccessionNumber:     %s',SET(NO).AccessionNumber)),...
    fixstring(sprintf('StudyUID:            %s',SET(NO).StudyUID)),...
    fixstring(sprintf('StudyID:             %s',SET(NO).StudyID)),...
    fixstring(sprintf('SeriesNumber:        %d',SET(NO).SeriesNumber)),...
    fixstring(sprintf('ResolutionX:         %0.5g [mm]',SET(NO).ResolutionX)),...
    fixstring(sprintf('ResolutionY:         %0.5g [mm]',SET(NO).ResolutionY)),...
    fixstring(sprintf('SliceThickness:      %0.5g [mm]',SET(NO).SliceThickness)),...
    fixstring(sprintf('SliceGap:            %0.5g [mm]',SET(NO).SliceGap)),...
    fixstring(sprintf('ImageOrientation:    %s',sprintf('%0.4f ',SET(NO).ImageOrientation(1:end)))),...
    fixstring(sprintf('ImagePosition:       %s',sprintf('%0.4f ',SET(NO).ImagePosition(1:end)))),...
    };
else
  %Default
  str = {
    fixstring(sprintf('FileName:            %s',SET(NO).FileName)),...
    fixstring(sprintf('OrigFileName:        %s',SET(NO).OrigFileName)),...
    fixstring(sprintf('Scanner:             %s',SET(NO).Scanner)),...
    fixstring(sprintf('FieldStrength:       %0.1f %s',SET(NO).FieldStrength,fieldunit)),...
    fixstring(sprintf('AcquisitionDate:     %s',SET(NO).PatientInfo.AcquisitionDate)),...
    fixstring(sprintf(['AcquisitionTime:     ', segtime2clock, ' [hh:mm:sec]'])),...
    fixstring(sprintf('XSize:               %d',SET(NO).XSize)),...
    fixstring(sprintf('YSize:               %d',SET(NO).YSize)),...
    fixstring(sprintf('ZSize:               %d',SET(NO).ZSize)),...
    fixstring(sprintf('TSize:               %d',SET(NO).TSize)),...
    fixstring(sprintf('TIncr:               %0.5g [ms]',1000*SET(NO).TIncr)),...
    fixstring(sprintf('TDelay:              %0.5g [ms]',1000*SET(NO).TDelay)),...
    fixstring(sprintf('FlipAngle:           %0.5g [degrees]',SET(NO).FlipAngle)),...
    fixstring(sprintf('AccessionNumber:     %s',SET(NO).AccessionNumber)),...
    fixstring(sprintf('StudyUID:            %s',SET(NO).StudyUID)),...
    fixstring(sprintf('StudyID:             %s',SET(NO).StudyID)),...
    fixstring(sprintf('SeriesNumber:        %d',SET(NO).SeriesNumber)),...
    fixstring(sprintf('EchoTime:            %0.5g [ms]',SET(NO).EchoTime(1))),...
    fixstring(sprintf('RepetitionTime:      %0.5g [ms]',SET(NO).RepetitionTime)),...
    fixstring(sprintf('InversionTime(mean): %0.5g [ms]',mean(SET(NO).InversionTime(:)))),...
    fixstring(sprintf('HeartRate:           %0.5g [bpm]',SET(NO).HeartRate)),...
    fixstring(sprintf('RRInterval:          %0.5g [ms]',SET(NO).RRInterval)),...
    fixstring(sprintf('BeatTime:            %0.5g [s]',SET(NO).BeatTime)),...
    fixstring(sprintf('ResolutionX:         %0.5g [mm]',SET(NO).ResolutionX)),...
    fixstring(sprintf('ResolutionY:         %0.5g [mm]',SET(NO).ResolutionY)),...
    fixstring(sprintf('SliceThickness:      %0.5g [mm]',SET(NO).SliceThickness)),...
    fixstring(sprintf('SliceGap:            %0.5g [mm]',SET(NO).SliceGap)),...
    fixstring(sprintf('ImageOrientation:    %s',sprintf('%0.4f ',SET(NO).ImageOrientation(1:end)))),...
    fixstring(sprintf('ImagePosition:       %s',sprintf('%0.4f ',SET(NO).ImagePosition(1:end)))),...
    fixstring(sprintf('ImagingTechnique:    %s',SET(NO).ImagingTechnique)),...
    fixstring(sprintf('ImageType:           %s',SET(NO).ImageType)),...
    fixstring(sprintf('ImageViewPlane:      %s',SET(NO).ImageViewPlane)),...
    fixstring(sprintf('Modality:            %s',SET(NO).Modality)),...
    fixstring(sprintf('OrgPathName:         %s',SET(NO).PathName)),...
    fixstring(sprintf('XMin:                %d',SET(NO).XMin)),...
    fixstring(sprintf('YMin:                %d',SET(NO).YMin)),...
    fixstring(sprintf('Cyclic:              %d',SET(NO).Cyclic)),...
    fixstring(sprintf('Rotated:             %d',SET(NO).Rotated)),...
    fixstring(sprintf('VENC:                %0.5g [cm/s]',SET(NO).VENC)),...
    fixstring(sprintf('SectorRotation:      %0.5g',SET(NO).SectorRotation)),...
    fixstring(sprintf('IntensityScaling:    %0.5g',SET(NO).IntensityScaling)),...
    fixstring(sprintf('IntensityOffset:     %0.5g',SET(NO).IntensityOffset))...
    };
end

%-------------------------------
function copy_Callback
%-------------------------------
%Copy info to clipboard
global DATA

gui = DATA.GUI.ImageInfo;

stri = gui.string;
stri = strrep(stri,' ',''); % remove spaces
stri = strrep(stri,':',sprintf('\t')); % Change ':' to tabs
segment('cell2clipboard',stri');

%-----------------------
function close_Callback
%-----------------------
%Close the GUI
global DATA

try
  close(DATA.GUI.ImageInfo);
catch
  close(gcbf);
end
DATA.GUI.ImageInfo = [];