function stri = removeforbiddenchars(stri)
%-----------------------------------------
%Remove forbidden characters from string (for filenames).

%Einar Heiberg
stri = upper(stri);
stri = deblank(stri);
stri(stri==' ')='_';
stri(stri=='Å') = 'A';
stri(stri=='Ä') = 'A';
stri(stri=='Ö') = 'O';
stri(stri=='É') = 'E';
stri(stri=='È') = 'E';

logind = ...
  (stri==':')|...
  (stri=='\')|...
  (stri=='/')|...
  (stri=='?')|...
  (stri=='*')|...
  (stri=='"')|...
  (stri=='<')|...
  (stri=='>')|...
  (stri=='|');

stri(logind)='-';
takeind = (stri>64 & stri<91) | (stri=='-') | (stri=='_') | (stri=='^') | (stri>47 & stri<58);
stri = stri(takeind);